name: run main.py

on:
  schedule:
    - cron: '0 * * * *' #per hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Removing previous chrome instances on runner 
        run: sudo apt purge google-chrome-stable  
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay
      - name: Install xvfb
        run: sudo apt-get install xvfb
          
      - name: execute py script # run main.py
        run: python scripts/oslo-applicatieprofiel-controle.py 
        
      - name: execute py script # run main.py
        run: python scripts/controle_dead_links.py 
              
      - name: e-mail
        run: git config --global user.email "samuel.vanackere@vlaanderen.be"
      - name: My name
        run: git config --global user.name "Samuel Van Ackere"
          
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Update logfiles" --allow-empty
      - name: fetch from main
        run: git fetch origin main
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          branch: main 
